import { definePreset } from '@primeuix/themes'

import Lara from '@primeuix/themes/lara' //themes

import '@/assets/tokens.css' // custom global styles

export default definePreset(Lara, {
  semantic: {
    colorScheme: {
      light: {
        primary: {
          50: 'var(--pipe-primary-50)',
          100: 'var(--pipe-primary-100)',
          200: 'var(--pipe-primary-200)',
          300: 'var(--pipe-primary-300)',
          400: 'var(--pipe-primary-400)',
          500: 'var(--pipe-primary-500)',
          600: 'var(--pipe-primary-700)',
          700: 'var(--pipe-primary-700)',
          800: 'var(--pipe-primary-800)',
          900: 'var(--pipe-primary-900)',
          950: 'var(--pipe-primary-950)',
        },
        secondary: {
          50: 'var(--pipe-secondary-50)',
          100: 'var(--pipe-secondary-100)',
          200: 'var(--pipe-secondary-200)',
          300: 'var(--pipe-secondary-300)',
          400: 'var(--pipe-secondary-400)',
          500: 'var(--pipe-secondary-500)',
          600: 'var(--pipe-secondary-700)',
          700: 'var(--pipe-secondary-700)',
          800: 'var(--pipe-secondary-800)',
          900: 'var(--pipe-secondary-900)',
          950: 'var(--pipe-secondary-950)',
        },
      },
      dark: {
        primary: {
          50: 'var(--pipe-primary-50)',
          100: 'var(--pipe-primary-100)',
          200: 'var(--pipe-primary-200)',
          300: 'var(--pipe-primary-300)',
          400: 'var(--pipe-primary-400)',
          500: 'var(--pipe-primary-500)',
          600: 'var(--pipe-primary-400)',
          700: 'var(--pipe-primary-700)',
          800: 'var(--pipe-primary-800)',
          900: 'var(--pipe-primary-900)',
          950: 'var(--pipe-primary-950)',
        },
        secondary: {
          50: 'var(--pipe-secondary-50)',
          100: 'var(--pipe-secondary-100)',
          200: 'var(--pipe-secondary-200)',
          300: 'var(--pipe-secondary-300)',
          400: 'var(--pipe-secondary-400)',
          500: 'var(--pipe-secondary-500)',
          600: 'var(--pipe-secondary-400)',
          700: 'var(--pipe-secondary-700)',
          800: 'var(--pipe-secondary-800)',
          900: 'var(--pipe-secondary-900)',
          950: 'var(--pipe-secondary-950)',
        },
      },
    },
    focusRing: {
      width: '2px',
      style: 'solid',
      color: '{primary.500}',
      offset: '2px',
    },
  },
  components: {
    button: {
      colorScheme: {
        primary: {
          light: {
            background: '{primary.500}',
            hoverBackground: '{primary.700}',
            activeBackground: '{primary.800}',
            borderColor: '{primary.500}',
            hoverBorderColor: '{primary.700}',
            activeBorderColor: '{primary.800}',
            color: '#ffffff',
            hoverColor: '#ffffff',
            activeColor: '#ffffff',
            focusRing: {
              color: '{primary.500}',
              shadow: '0 0 0 0.2rem color-mix(in srgb, {primary.500}, transparent 50%)',
            },
          },
          dark: {
            background: '{primary.500}',
            hoverBackground: '{primary.400}',
            activeBackground: '{primary.300}',
            borderColor: '{primary.500}',
            hoverBorderColor: '{primary.400}',
            activeBorderColor: '{primary.300}',
            color: '#ffffff',
            hoverColor: '#ffffff',
            activeColor: '#ffffff',
            focusRing: {
              color: '{primary.400}',
              shadow: '0 0 0 0.2rem color-mix(in srgb, {primary.400}, transparent 50%)',
            },
          },
        },
        secondary: {
          light: {
            background: '{secondary.500}',
            hoverBackground: '{secondary.700}',
            activeBackground: '{secondary.800}',
            borderColor: '{secondary.500}',
            hoverBorderColor: '{secondary.700}',
            activeBorderColor: '{secondary.800}',
            color: '#ffffff',
            hoverColor: '#ffffff',
            activeColor: '#ffffff',
            focusRing: {
              color: '{secondary.500}',
              shadow: '0 0 0 0.2rem color-mix(in srgb, {secondary.500}, transparent 50%)',
            },
          },
          dark: {
            background: '{secondary.500}',
            hoverBackground: '{secondary.400}',
            activeBackground: '{secondary.300}',
            borderColor: '{secondary.500}',
            hoverBorderColor: '{secondary.400}',
            activeBorderColor: '{secondary.300}',
            color: '#ffffff',
            hoverColor: '#ffffff',
            activeColor: '#ffffff',
            focusRing: {
              color: '{secondary.400}',
              shadow: '0 0 0 0.2rem color-mix(in srgb, {secondary.400}, transparent 50%)',
            },
          },
        },
      } as Record<string, unknown>,
    },
    inputtext: {
      colorScheme: {
        light: {
          background: '{surface.0}',
          disabledBackground: '{surface.200}',
          filledBackground: '{surface.50}',
          filledFocusBackground: '{surface.0}',
          borderColor: '{surface.300}',
          hoverBorderColor: '{primary.500}',
          focusBorderColor: '{primary.500}',
          invalidBorderColor: '{red.500}',
          color: '{surface.700}',
          disabledColor: '{surface.500}',
          placeholderColor: '{surface.500}',
          shadow: '0 0 #0000, 0 0 #0000, 0 1px 2px 0 rgba(18, 18, 23, 0.05)',
        },
        dark: {
          background: '{surface.950}',
          disabledBackground: '{surface.700}',
          filledBackground: '{surface.800}',
          filledFocusBackground: '{surface.950}',
          borderColor: '{surface.600}',
          hoverBorderColor: '{primary.400}',
          focusBorderColor: '{primary.400}',
          invalidBorderColor: '{red.400}',
          color: '{surface.0}',
          disabledColor: '{surface.400}',
          placeholderColor: '{surface.400}',
          shadow: '0 0 #0000, 0 0 #0000, 0 1px 2px 0 rgba(18, 18, 23, 0.05)',
        },
      } as Record<string, unknown>,
    },
    menubar: {
      colorScheme: {
        light: {
          background: '{surface.100}',
          color: '{surface.900}',
          hoverBackground: '{surface.200}',
          hoverColor: '{surface.900}',
          activeBackground: '{surface.300}',
          activeColor: '{surface.900}',
          borderColor: '{surface.300}',
        },
        dark: {
          background: '{surface.800}',
          color: '{surface.100}',
          hoverBackground: '{surface.700}',
          hoverColor: '{surface.100}',
          activeBackground: '{surface.600}',
          activeColor: '{surface.100}',
          borderColor: '{surface.600}',
        },
      } as Record<string, unknown>,
    },
  },
})
