import { definePreset } from '@primeuix/themes';
import Lara from '@primeuix/themes/lara';

import '@/assets/tokens.css';

export default definePreset(Lara, {
  semantic: {
    colorScheme: {
      light: {
        primary: {
          50: 'var(--magenta-50)',
          100: 'var(--magenta-100)',
          200: 'var(--magenta-200)',
          300: 'var(--magenta-300)',
          400: 'var(--magenta-400)',
          500: 'var(--magenta-500)',
          600: 'var(--magenta-600)',
          700: 'var(--magenta-700)',
          800: 'var(--magenta-800)',
          900: 'var(--magenta-900)',
          950: 'var(--magenta-950)',
        },
        danger: {
          50: 'var(--danger-50)',
          100: 'var(--danger-100)',
          200: 'var(--danger-200)',
          300: 'var(--danger-300)',
          400: 'var(--danger-400)',
          500: 'var(--danger-500)',
          600: 'var(--danger-600)',
          700: 'var(--danger-700)',
          800: 'var(--danger-800)',
          900: 'var(--danger-900)',
          950: 'var(--danger-950)',
        },
        neutral: {
          50: 'var(--neutral-50)',
          100: 'var(--neutral-100)',
          200: 'var(--neutral-200)',
          300: 'var(--neutral-300)',
          400: 'var(--neutral-400)',
          500: 'var(--neutral-500)',
          600: 'var(--neutral-600)',
          700: 'var(--neutral-700)',
          800: 'var(--neutral-800)',
          900: 'var(--neutral-900)',
          950: 'var(--neutral-950)',
        },
        surface: {
          ground: 'var(--surface-ground)',
          section: 'var(--surface-alt)',
          card: 'var(--surface-card)',
          overlay: 'var(--surface-overlay)',
          header: 'var(--surface-header)',
          border: 'var(--surface-border)',
          ring: 'var(--focus-ring)',
        },
        text: {
          primary: 'var(--text-primary)',
          secondary: 'var(--text-secondary)',
          muted: 'var(--text-muted)',
          inverse: 'var(--text-inverse)',
          onAlt: 'var(--text-on-alt)',
        },
      },
      dark: {
        primary: {
          50: 'var(--magenta-50)',
          100: 'var(--magenta-100)',
          200: 'var(--magenta-200)',
          300: 'var(--magenta-300)',
          400: 'var(--magenta-400)',
          500: 'var(--magenta-500)',
          600: 'var(--magenta-600)',
          700: 'var(--magenta-700)',
          800: 'var(--magenta-800)',
          900: 'var(--magenta-900)',
          950: 'var(--magenta-950)',
        },
        danger: {
          50: 'var(--danger-50)',
          100: 'var(--danger-100)',
          200: 'var(--danger-200)',
          300: 'var(--danger-300)',
          400: 'var(--danger-400)',
          500: 'var(--danger-500)',
          600: 'var(--danger-600)',
          700: 'var(--danger-700)',
          800: 'var(--danger-800)',
          900: 'var(--danger-900)',
          950: 'var(--danger-950)',
        },
        neutral: {
          50: 'var(--neutral-50)',
          100: 'var(--neutral-100)',
          200: 'var(--neutral-200)',
          300: 'var(--neutral-300)',
          400: 'var(--neutral-400)',
          500: 'var(--neutral-500)',
          600: 'var(--neutral-600)',
          700: 'var(--neutral-700)',
          800: 'var(--neutral-800)',
          900: 'var(--neutral-900)',
          950: 'var(--neutral-950)',
        },
        surface: {
          ground: 'var(--surface-ground)',
          section: 'var(--surface-alt)',
          card: 'var(--surface-card)',
          overlay: 'var(--surface-overlay)',
          header: 'var(--surface-header)',
          border: 'var(--surface-border)',
          ring: 'var(--focus-ring)',
        },
        text: {
          primary: 'var(--text-primary)',
          secondary: 'var(--text-secondary)',
          muted: 'var(--text-muted)',
          inverse: 'var(--text-inverse)',
          onAlt: 'var(--text-on-alt)',
        },
      },
    },
  },
});
